### PR TITLE
Integrate Welcome and Greeting Bot 

### LINKED ISSUE #1: Integrate Welcome and Greeting Bot
Hi @Novartus 

I would like to contribute to this amazing project
I can add a config file and integrate the bot so that whenever a new user opens a issue or pr , the bot will comment and greet the user with a proper message

Let me know if you are interested

Kindly do assign me
Kindly do add the DWOC and Level label

### PR DESCRIPTION
**Pull request by akrish4**
Fixed : #1 

Kindly do check and merge it 

Kindly add the same labels in pr too

### CODE REVIEW

**Comment by akrish4** [comment]
Hi @Novartus 
Kindly add the DWOC and Level-4 label in pr too

**Comment by Novartus** [comment]
@akrish4 
Update on label:  I've changed the label according to guidelines

**Comment by akrish4** [comment]
> @akrish4
> Update on label: I've changed the label according to guidelines

okay thats totally fine

**Comment by akrish4** [comment]
> @akrish4
> Update on label: I've changed the label according to guidelines

you atleast commented here to notify about update in label , thank you @Novartus  
some ppl just update it without letting me know , btw Level-4 is not required for this issue ? i don't know so i am asking , kindly tell me

**Comment by Novartus** [comment]
> > @akrish4
> > Update on label: I've changed the label according to guidelines
> 
> you atleast commented here to notify about update in label , thank you @Novartus  
> some ppl just update it without letting me know , btw Level-4 is not required for this issue ? i don't know so i am asking , kindly tell me 

I crossed check the details with guidelines and it is level 1 issue not Level-4 .

**Pull request merged**
